apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  deploy-app1:
    steps:
      - name: Deploy cbpautomation/python-hello-world-docker
        if: ${{ fromJSON(inputs.manifest)['cbpautomation/python-hello-world-docker'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          artifact-id: "${{ fromJSON(inputs.manifest)['cbpautomation/python-hello-world-docker'].id }}"
          target-environment: "${{ inputs.environment }}"
