apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "0.0.181"
          url: "docker.io/cbpautomation/python-hello-world-docker:0.0.181"
          digest: "sha256:2dabea40075b95bde306afbd6b7eec1f61302d5216a29c7d84beb46f79db0cb7"
          target-environment: "PREPROD"