apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "21.05.36"
          url: "docker.io/cbpautomation/python-hello-world-docker:21.05.36"
          digest: "sha256:ebe363aadfbf3add0f696299d1477dcf113aa98ace3f843398feb7c6c90681ad"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "PROD"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

