apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "25.19.24"
          digest: "sha256:532a89d4393fb8cfef4d6079b0375116c3ea1ee9d5ff1453433a8c4131eb17c0"
          url: "docker.io/cbpautomation/python-hello-world-docker:25.19.24"
          target-environment: "PROD"

