apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.12.26"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.12.26"
          digest: "sha256:93e2c1f15242d1cb791d5caa83a8b56c5f749a55267c8dadc83091ee8ebfebef"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.12.26"
          digest: "sha256:93e2c1f15242d1cb791d5caa83a8b56c5f749a55267c8dadc83091ee8ebfebef"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.12.26"
          target-environment: "PROD"

