apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout

      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Set up Docker Hub registry
        kind: deploy
        with:
          registry: https://index.docker.io/v1/
          username: cbpautomation
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: cloudbees-io/kaniko/.cloudbees/testing
        name: Push image to OCI registry
        with:
          destination: index.docker.io/cbpautomation/python-hello-world-docker:${{cloudbees.version}}
          labels: app=cbp

      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          apk update && apk add --no-cache curl jq
          echo '{"user": "thanan", "password": "pwd", "id": 2345, "token": "token"}' | jq '.id'


