apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-prod/prod-python-helloworld/.cloudbees/workflows/callable-workflow-1122fc96-a299-4649-a08a-c2b0bd3c05a8.yaml
    