apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: insights-test-prod/prod-python-hello-world/.cloudbees/workflows/callable-workflow-53404f0c-1aba-4522-866e-a7225c7a8099.yaml
    